---
title: "ANGSD - HW Week 7"
author: "Tomer M. Yaron"
date: "2/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown - HW Week 7 - Tomer M. Yaron

## 1 - running featureCounts per exon for the 10 sanples

```{featureCounts}

ln -s /home/frd2007/ANGSD_2019/alignment
ln -s /home/frd2007/ANGSD_2019/RNA-seq/refGenome_S_cerevisiae/sacCer3.gtf

for f in ./databases/alignment/*.sortedByCoord.out.bam
  do featureCounts -t exon -f -a ./databases/sacCer3.gtf -o /athena/elementolab/scratch/toy2005/angsd/hw6/counts/$(echo $f | cut -d"/" -f4 | cut -d"." -f1)_counts.txt $f
done

scp -r toy2005@pascal.med.cornell.edu:/athena/elementolab/scratch/toy2005/angsd/hw6/counts ./

```

_____________________________________________________________________

## 2 - Counts barplot

```{r, counts_statistics}

library(ggplot2)
library(reshape2)

file_names <- dir('./counts/', pattern =".summary")
m <- matrix(0, ncol = 3, nrow = length(file_names))
exon_counts <- data.frame(m)
colnames(exon_counts) <- c('Assigned','Unassigned_NoFeatures','Unassigned_Ambiguity')
rownames(exon_counts) <- lapply(strsplit(file_names,'_A'), function(x) x[1])

for (f in file_names){
  sample <- strsplit(f,'_A')[[1]][1]
  counts <- read.table(paste0('./counts/',f), row.names = 1, header = TRUE)
  for (att in colnames(exon_counts)){
    exon_counts[sample,att] <- counts[att,]
  }
}

class_exon_counts <- data.frame(m)
colnames(class_exon_counts) <- c('Assigned','Unassigned_NoFeatures','Unassigned_Ambiguity')
rownames(class_exon_counts) <- lapply(strsplit(file_names,'_A'), function(x) x[1])
original_class_exon_counts <- read.table('./featCounts_Gierlinski_exons.txt.summary', row.names = 1, header = TRUE)

for (f in colnames(original_class_exon_counts)){
  sample <- tail(strsplit(strsplit(f,'_A')[[1]][1],'[.]')[[1]], n=1)
  for (att in colnames(exon_counts)){
    class_exon_counts[sample,att] <- original_class_exon_counts[att,f]
  }
}

exon_counts$Category  <- row.names(exon_counts)
exon_counts_melt <- melt(exon_counts, value.name="Count", variable.name="Variable")
ggplot(data=exon_counts_melt, aes(x=Category, y=Count, fill=Variable)) + geom_bar(stat="identity", position=position_dodge())

class_exon_counts$Category  <- row.names(class_exon_counts)
class_exon_counts_melt <- melt(class_exon_counts, value.name="Count", variable.name="Variable")
ggplot(data=class_exon_counts_melt, aes(x=Category, y=Count, fill=Variable)) + geom_bar(stat="identity", position=position_dodge())


```

_____________________________________________________________________















